package com.echoteam.MEC.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.sql.Timestamp;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AnalysisResponse {

    // Unique ID for this analysis task, generated by the backend
    private String requestId;

    // Phone number of the caller, provided by the frontend
    private String phoneNumber;

    // Name of the caller, extracted or inferred by the LLM
    private String callerName;

    // The time when the emergency call was reported
    private Timestamp timeReported;

    // Type of incident (e.g., FIRE / ACCIDENT / MEDICAL / CRIME / OTHER)
    private String incidentType;

    // A brief description of the incident, summarized by the LLM
    private String incidentDescription;

    // Reported address or location of the incident
    private String address;

    // Nearby landmark or notable place related to the incident
    private String landmark;

    // Number of victims involved in the incident
    private Integer victimCount;

    // Description of victims (e.g., age, gender, clothing)
    private String victimDescription;

    // Severity of injuries (e.g., Minor / Serious / Unknown)
    private String injurySeverity;

    // Whether the victim is conscious
    private Boolean isConscious;

    // Whether the victim is breathing
    private Boolean isBreathing;

    // Whether the situation is ongoing or still active
    private Boolean isOngoing;

    // Whether the incident involves fire
    private Boolean isFire;

    // Priority or urgency level (1–100), assessed by the LLM
    private Integer urgencyLevel;

    // List of key phrases or entities extracted from the transcript
    private List<String> keyPhrases;

    // Confidence level (0–100) indicating LLM’s certainty in its analysis
    private int confidence;

    // Identifier of the AI model or system that processed this analysis
    private String processedBy;
}